### PR TITLE
Changed Memory to better fit accurate model of memory and remove unes…

### PR DESCRIPTION
**Pull request by fdaniels110**
…sesary Block object.  Moved starting location for process to process itself to reflect real process. Changes allow for lower access into memory and more powerful methods that give more information to caller.  Documented each method in Memory.java with purpose and reasoing.

### CODE REVIEW

**Comment by flip40** [comment]
Saying the Block object is unnecessary is like saying println is unnecessary, just add +"\n" to the end of a print statement like every other programming language. Blocks are not necessary, but they are a useful abstraction.

I disagree with these methods being more powerful and providing more information to the caller. I think we can say this is false as providing an Int instead of two Ints encapsulated in an object is quite literally less information. Instead of returning a Block with index and size in a single object, I must call getNextBlock for an index of a block, followed by checkMem to get the size of that block. You do, however, provide the ability to iterate over all blocks, whereas I had only implemented a method that found blocks that were free.

I also disagree with this being a more accurate model of memory. The model is quite literally just the array, 100 slots for 100mb. Your changes mirror mine in the sense that we are both providing methods that assist in navigating the memory array.

On the other hand, I do realize that the methods I provided are most convenient for FirstFit and BestFit. I did not provide a method that usefully allows finding a free block starting from the last index or block that was used.

Regardless, if you want to have a lower level control of the memory as it makes sense to you for completing your algorithm, feel free to add the methods to allow that (consider overloading those that share the same name), but don't overwrite the Block object or the methods using it. I don't want to get in the way of anyone completing their part on the assignment, but by the same token I don't want to have to rewrite my own part because we removed Blocks (and possibly Erick's, if he has been using the Blocks).

On the whole the changes to Process and removeProcess are fine, as it makes removal more efficient than checking all memory spaces for that process, but if we are keeping blocks we will need to make changes to the Block version of swapProcess as well.

**Comment by fdaniels110** [comment]
I'll overload the methods.  I'm probably focusing way too much on making it more representative of actual memory. I'll fix it

**Comment by flip40** [comment]
Hm, I'll take a look. It is too bad I didn't think of this until hours after my comment, but I think I can actually re-add block implementation without touching most of what you did. For example, I can provide a swapProcess that takes a block instead of an int index that just calls your swapProcess and passing the block index in.... I'll take a look at your changes and see where we are at with that at this point.

**Comment by flip40** [comment]
Yea, hold up for like 30 minutes, let me finish my changes and see if you like them and we can merge my branch back into yours if you do. I think you'll find it agreeable, as it pretty much leaves your work intact and adds the old block functionality in as convenience functions that just call your functions. Best of both worlds, I think.

**Comment by flip40** [comment]
Ok got it done, check #4, if you like it give it a merge. In short it adds back the convenience of using blocks without making any significant changes to what your code is now (other than returning a Block on getNextBlock, which is explained in the PR).

**Comment by flip40** [comment]
Awesome, I'll merge this then.

**Pull request merged**
